// <auto-generated/>
// Polyfill for init-only properties and record structs when targeting netstandard2.0.

// ReSharper disable once CheckNamespace
namespace System.Runtime.CompilerServices
{
    internal static class IsExternalInit
    {
    }
}
