using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Volt.Core.Generators;

/// <summary>
/// Source generator that discovers all Model&lt;T&gt; subclasses in the Models/ folder
/// and auto-registers them as DbSet&lt;T&gt; properties on the application's DbContext.
/// </summary>
[Generator]
public class ModelDiscoveryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var modelClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => IsClassDeclaration(node),
                transform: static (ctx, _) => GetModelInfo(ctx))
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        var collected = modelClasses.Collect();

        context.RegisterSourceOutput(collected, static (spc, models) =>
        {
            if (models.IsEmpty) return;
            GenerateDbContextRegistration(spc, models);
        });
    }

    private static bool IsClassDeclaration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDecl
            && classDecl.BaseList is not null;
    }

    private static ModelInfo? GetModelInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null) return null;

        var baseType = symbol.BaseType;
        if (baseType is null || !baseType.IsGenericType) return null;

        var baseTypeName = baseType.ConstructedFrom.ToDisplayString();
        if (baseTypeName != "Volt.Core.Model<T>") return null;

        var filePath = classDecl.SyntaxTree.FilePath;
        var isInModelsFolder = filePath.Replace("\\", "/").Contains("/Models/");
        if (!isInModelsFolder) return null;

        return new ModelInfo(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString());
    }

    private static void GenerateDbContextRegistration(
        SourceProductionContext context,
        ImmutableArray<ModelInfo> models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();

        var namespaces = models
            .Select(m => m.Namespace)
            .Distinct()
            .OrderBy(n => n);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Volt.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated partial DbContext with DbSet properties for discovered models.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class VoltModelRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static ModelBuilder ApplyVoltModels(this ModelBuilder modelBuilder)");
        sb.AppendLine("    {");

        foreach (var model in models)
        {
            sb.AppendLine($"        modelBuilder.Entity<{model.Name}>();");
        }

        sb.AppendLine("        return modelBuilder;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static readonly System.Type[] DiscoveredModelTypes = new[]");
        sb.AppendLine("    {");

        for (int i = 0; i < models.Length; i++)
        {
            var comma = i < models.Length - 1 ? "," : "";
            sb.AppendLine($"        typeof({models[i].Name}){comma}");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("VoltModelRegistration.g.cs", sb.ToString());
    }
}

internal readonly record struct ModelInfo(string Name, string Namespace);
