using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Volt.Core.Generators;

/// <summary>
/// Source generator that discovers ResourceController subclasses in Controllers/
/// and generates RESTful route registrations.
/// Convention: ArticlesController -> /articles with standard CRUD routes.
/// </summary>
[Generator]
public class RouteRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var controllerClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetControllerInfo(ctx))
            .Where(static c => c is not null)
            .Select(static (c, _) => c!.Value);

        var collected = controllerClasses.Collect();

        context.RegisterSourceOutput(collected, static (spc, controllers) =>
        {
            if (controllers.IsEmpty) return;
            GenerateRouteRegistration(spc, controllers);
        });
    }

    private static ControllerInfo? GetControllerInfo(GeneratorSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
        if (symbol is null || symbol.IsAbstract) return null;

        if (!symbol.Name.EndsWith("Controller")) return null;

        var filePath = classDecl.SyntaxTree.FilePath.Replace("\\", "/");
        var isInControllersFolder = filePath.Contains("/Controllers/");
        if (!isInControllersFolder) return null;

        var isResourceController = IsResourceControllerSubclass(symbol);
        var isApiController = IsApiResourceControllerSubclass(symbol);

        if (!isResourceController && !isApiController) return null;

        var resourceName = symbol.Name
            .Replace("Controller", "")
            .ToLowerInvariant();

        var apiPrefix = "";
        if (isApiController)
        {
            var segments = ExtractApiPrefix(filePath);
            apiPrefix = segments ?? "/api";
        }

        return new ControllerInfo(
            symbol.Name,
            symbol.ContainingNamespace.ToDisplayString(),
            resourceName,
            isApiController,
            apiPrefix);
    }

    private static bool IsResourceControllerSubclass(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            var displayName = current.ConstructedFrom.ToDisplayString();
            if (displayName == "Volt.Web.Controllers.ResourceController<T>")
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static bool IsApiResourceControllerSubclass(INamedTypeSymbol symbol)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            var displayName = current.ConstructedFrom.ToDisplayString();
            if (displayName == "Volt.Web.Controllers.ApiResourceController<T>")
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static string? ExtractApiPrefix(string filePath)
    {
        var parts = filePath.Split('/');
        var apiIndex = -1;
        for (int i = 0; i < parts.Length; i++)
        {
            if (parts[i] == "Api" || parts[i] == "api")
            {
                apiIndex = i;
                break;
            }
        }

        if (apiIndex < 0) return null;

        var segments = new System.Collections.Generic.List<string>();
        for (int i = apiIndex; i < parts.Length - 1; i++)
        {
            segments.Add(parts[i].ToLowerInvariant());
        }

        return "/" + string.Join("/", segments);
    }

    private static void GenerateRouteRegistration(
        SourceProductionContext context,
        ImmutableArray<ControllerInfo> controllers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();

        var namespaces = controllers
            .Select(c => c.Namespace)
            .Distinct()
            .OrderBy(n => n);

        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }

        sb.AppendLine();
        sb.AppendLine("namespace Volt.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated route registrations for convention-discovered controllers.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class VoltRouteRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapVoltRoutes(this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var controller in controllers)
        {
            var prefix = controller.IsApi
                ? $"{controller.ApiPrefix}/{controller.ResourceName}"
                : $"/{controller.ResourceName}";

            sb.AppendLine($"        // Routes for {controller.Name}");
            sb.AppendLine($"        endpoints.MapControllerRoute(\"{controller.ResourceName}_index\", \"{prefix}\", new {{ controller = \"{controller.ResourceName}\", action = \"Index\" }});");
            sb.AppendLine($"        endpoints.MapControllerRoute(\"{controller.ResourceName}_create\", \"{prefix}\", new {{ controller = \"{controller.ResourceName}\", action = \"Create\" }});");
            sb.AppendLine($"        endpoints.MapControllerRoute(\"{controller.ResourceName}_new\", \"{prefix}/new\", new {{ controller = \"{controller.ResourceName}\", action = \"New\" }});");
            sb.AppendLine($"        endpoints.MapControllerRoute(\"{controller.ResourceName}_show\", \"{prefix}/{{id}}\", new {{ controller = \"{controller.ResourceName}\", action = \"Show\" }});");
            sb.AppendLine($"        endpoints.MapControllerRoute(\"{controller.ResourceName}_edit\", \"{prefix}/{{id}}/edit\", new {{ controller = \"{controller.ResourceName}\", action = \"Edit\" }});");
            sb.AppendLine($"        endpoints.MapControllerRoute(\"{controller.ResourceName}_update\", \"{prefix}/{{id}}\", new {{ controller = \"{controller.ResourceName}\", action = \"Update\" }});");
            sb.AppendLine($"        endpoints.MapControllerRoute(\"{controller.ResourceName}_destroy\", \"{prefix}/{{id}}\", new {{ controller = \"{controller.ResourceName}\", action = \"Destroy\" }});");
            sb.AppendLine();
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public static readonly (string Name, string Method, string Pattern)[] Routes = new[]");
        sb.AppendLine("    {");

        foreach (var controller in controllers)
        {
            var prefix = controller.IsApi
                ? $"{controller.ApiPrefix}/{controller.ResourceName}"
                : $"/{controller.ResourceName}";

            sb.AppendLine($"        (\"{controller.ResourceName}#index\", \"GET\", \"{prefix}\"),");
            sb.AppendLine($"        (\"{controller.ResourceName}#create\", \"POST\", \"{prefix}\"),");
            sb.AppendLine($"        (\"{controller.ResourceName}#new\", \"GET\", \"{prefix}/new\"),");
            sb.AppendLine($"        (\"{controller.ResourceName}#show\", \"GET\", \"{prefix}/{{id}}\"),");
            sb.AppendLine($"        (\"{controller.ResourceName}#edit\", \"GET\", \"{prefix}/{{id}}/edit\"),");
            sb.AppendLine($"        (\"{controller.ResourceName}#update\", \"PUT\", \"{prefix}/{{id}}\"),");
            sb.AppendLine($"        (\"{controller.ResourceName}#destroy\", \"DELETE\", \"{prefix}/{{id}}\"),");
        }

        sb.AppendLine("    };");
        sb.AppendLine("}");

        context.AddSource("VoltRouteRegistration.g.cs", sb.ToString());
    }
}

internal readonly record struct ControllerInfo(
    string Name,
    string Namespace,
    string ResourceName,
    bool IsApi,
    string ApiPrefix);
